<?php

declare(strict_types=1);

use Illuminate\Contracts\Pagination\LengthAwarePaginator;
use Illuminate\Support\Collection;
use Nvl\Auth\Actions\Rbac\ListPermissionsAction;
use Nvl\Auth\Actions\Rbac\ListRolesAction;
use Nvl\Auth\Data\Display\PermissionListItemData;
use Nvl\Auth\Data\Display\RoleListItemData;
use Nvl\Content\Actions\GetContentBlockAction;
use Nvl\Content\Actions\ListContentBlocksAction;
use Nvl\Content\Actions\ListContentPlacementsAction;
use Nvl\Content\Content;
use Nvl\Content\Data\ContentBlockData;
use Nvl\Content\Data\ContentPlacementData;
use Nvl\Content\Facades\Content as ContentFacade;
use Nvl\Pages\Actions\GetPageAction;
use Nvl\Pages\Actions\ListPagesAction;
use Nvl\Pages\Data\PageData;
use Nvl\Seo\Actions\GetSeoProfileAction;
use Nvl\Seo\Actions\ListSeoProfilesAction;
use Nvl\Seo\Data\SeoProfileData;
use Nvl\Suite\Console\Commands\SuiteConfigureCommand;

return [
    'schema' => 'nvl-consumer-api-deprecations-v1',
    'final_1x' => [
        'version' => '1.0.7',
        'tag' => 'v1.0.7',
        'published_source' => '983ffbc8a648584a12ee0e3434e78715c6aac478',
        'prepared_source' => 'd8feceecc02f436772dca74b260704a535bceca6',
        'warnings' => 'not_published',
    ],
    'deprecations' => [
        'nvl-suite.modules.<omitted>' => [
            'kind' => 'behavior',
            'package' => 'suite',
            'since' => '1.0.7',
            'removed' => '2.0',
            'old_return' => 'omitted => enabled by the 1.x compatibility fallback',
            'new_return' => 'omitted => disabled unless dependency-enabled by an explicit root',
            'replacement' => SuiteConfigureCommand::class,
            'replacement_api' => 'php artisan nvl:suite:configure --profile=full-suite --full --write --force',
            'contract' => [
                'surface' => 'command',
                'class' => SuiteConfigureCommand::class,
                'method' => 'handle',
                'parameters' => [
                    'Nvl\\Suite\\Services\\SuiteConfigurationRenderer $renderer',
                    'Nvl\\Suite\\Support\\SuiteModuleCatalog $catalog',
                ],
                'return_type' => 'int',
                'command_signature' => 'nvl:suite:configure {--profile= : Start with a documented installation profile} {--add=* : Add a module and its transitive dependencies} {--remove=* : Exclude a module when no retained root requires it} {--minimal : Render only profile, include, and exclude} {--full : Render every resolved module boolean} {--path= : Destination inside the application; defaults to config/nvl-suite.php} {--write : Atomically write the destination instead of previewing it} {--force : Allow --write to replace an existing file after showing its diff} {--format=table : Output format: table or json}',
            ],
            'test_evidence' => [
                'tests/Feature/SuiteDiagnosticsTest.php',
                'tests/Feature/SuiteConfigurationWriterTest.php',
            ],
            'guide_anchor' => 'make-every-legacy-module-decision-explicit',
        ],
        'Nvl\\Auth\\Actions\\Rbac\\ListRolesAction::execute' => [
            'kind' => 'return-shape',
            'package' => 'auth',
            'since' => '1.0.7',
            'removed' => '2.0',
            'old_return' => 'Illuminate\\Contracts\\Pagination\\LengthAwarePaginator<int, Nvl\\Auth\\Models\\Role>',
            'new_return' => 'Illuminate\\Contracts\\Pagination\\LengthAwarePaginator<int, Nvl\\Auth\\Data\\Display\\RoleListItemData>',
            'replacement' => RoleListItemData::class,
            'replacement_api' => 'Nvl\\Auth\\Actions\\Rbac\\ListRolesAction::execute(Authenticatable $actor, ?string $search = null, int $perPage = 25)',
            'contract' => [
                'surface' => 'method',
                'class' => ListRolesAction::class,
                'method' => 'execute',
                'parameters' => [
                    'Illuminate\\Contracts\\Auth\\Authenticatable $actor',
                    '?string $search = null',
                    'int $perPage = 25',
                ],
                'return_type' => LengthAwarePaginator::class,
                'generic_return' => 'LengthAwarePaginator<int, RoleListItemData>',
            ],
            'test_evidence' => ['packages/nvl/auth/tests/Feature/RbacManagementTest.php'],
            'guide_anchor' => 'auth-role-and-permission-list-results',
        ],
        'Nvl\\Auth\\Actions\\Rbac\\ListPermissionsAction::execute' => [
            'kind' => 'return-shape',
            'package' => 'auth',
            'since' => '1.0.7',
            'removed' => '2.0',
            'old_return' => 'Illuminate\\Contracts\\Pagination\\LengthAwarePaginator<int, Nvl\\Auth\\Models\\Permission>',
            'new_return' => 'Illuminate\\Contracts\\Pagination\\LengthAwarePaginator<int, Nvl\\Auth\\Data\\Display\\PermissionListItemData>',
            'replacement' => PermissionListItemData::class,
            'replacement_api' => 'Nvl\\Auth\\Actions\\Rbac\\ListPermissionsAction::execute(Authenticatable $actor, ?string $search = null, ?string $group = null, int $perPage = 25)',
            'contract' => [
                'surface' => 'method',
                'class' => ListPermissionsAction::class,
                'method' => 'execute',
                'parameters' => [
                    'Illuminate\\Contracts\\Auth\\Authenticatable $actor',
                    '?string $search = null',
                    '?string $group = null',
                    'int $perPage = 25',
                ],
                'return_type' => LengthAwarePaginator::class,
                'generic_return' => 'LengthAwarePaginator<int, PermissionListItemData>',
            ],
            'test_evidence' => ['packages/nvl/auth/tests/Feature/RbacManagementTest.php'],
            'guide_anchor' => 'auth-role-and-permission-list-results',
        ],
        'Nvl\\Pages\\Actions\\GetPageAction::execute' => [
            'kind' => 'return-shape',
            'package' => 'pages',
            'since' => '1.0.7',
            'removed' => '2.0',
            'old_return' => 'Nvl\\Pages\\Models\\Page',
            'new_return' => 'Nvl\\Pages\\Data\\PageData',
            'replacement' => PageData::class,
            'replacement_api' => 'Nvl\\Pages\\Actions\\GetPageAction::execute(Page|string $page, PageActorData $actor): PageData',
            'contract' => [
                'surface' => 'method',
                'class' => GetPageAction::class,
                'method' => 'execute',
                'parameters' => [
                    'Nvl\\Pages\\Models\\Page|string $page',
                    'Nvl\\Pages\\Data\\PageActorData $actor',
                ],
                'return_type' => PageData::class,
            ],
            'test_evidence' => ['packages/nvl/pages/tests/Feature/PagesPackageTest.php'],
            'guide_anchor' => 'pages-read-results',
        ],
        'Nvl\\Pages\\Actions\\ListPagesAction::execute' => [
            'kind' => 'return-shape',
            'package' => 'pages',
            'since' => '1.0.7',
            'removed' => '2.0',
            'old_return' => 'Illuminate\\Contracts\\Pagination\\LengthAwarePaginator<int, Nvl\\Pages\\Models\\Page>',
            'new_return' => 'Illuminate\\Contracts\\Pagination\\LengthAwarePaginator<int, Nvl\\Pages\\Data\\PageData>',
            'replacement' => PageData::class,
            'replacement_api' => 'Nvl\\Pages\\Actions\\ListPagesAction::execute(FilterSet $filters, string $site, PageActorData $actor, int $perPage = 25)',
            'contract' => [
                'surface' => 'method',
                'class' => ListPagesAction::class,
                'method' => 'execute',
                'parameters' => [
                    'Nvl\\Filterable\\Data\\FilterSet $filters',
                    'string $site',
                    'Nvl\\Pages\\Data\\PageActorData $actor',
                    'int $perPage = 25',
                ],
                'return_type' => LengthAwarePaginator::class,
                'generic_return' => 'LengthAwarePaginator<int, PageData>',
            ],
            'test_evidence' => ['packages/nvl/pages/tests/Feature/PagesPackageTest.php'],
            'guide_anchor' => 'pages-read-results',
        ],
        'Nvl\\Content\\Actions\\GetContentBlockAction::execute' => [
            'kind' => 'return-shape',
            'package' => 'content',
            'since' => '1.0.7',
            'removed' => '2.0',
            'old_return' => 'Nvl\\Content\\Models\\ContentBlock',
            'new_return' => 'Nvl\\Content\\Data\\ContentBlockData',
            'replacement' => ContentBlockData::class,
            'replacement_api' => 'Nvl\\Content\\Actions\\GetContentBlockAction::execute(ContentBlock|string $block, ContentActorData $actor): ContentBlockData',
            'contract' => [
                'surface' => 'method',
                'class' => GetContentBlockAction::class,
                'method' => 'execute',
                'parameters' => [
                    'Nvl\\Content\\Models\\ContentBlock|string $block',
                    'Nvl\\Content\\Data\\ContentActorData $actor',
                ],
                'return_type' => ContentBlockData::class,
            ],
            'test_evidence' => ['packages/nvl/content/tests/Feature/ContentContractRegressionTest.php'],
            'guide_anchor' => 'content-read-results',
        ],
        'Nvl\\Content\\Actions\\ListContentBlocksAction::execute' => [
            'kind' => 'return-shape',
            'package' => 'content',
            'since' => '1.0.7',
            'removed' => '2.0',
            'old_return' => 'Illuminate\\Contracts\\Pagination\\LengthAwarePaginator<int, Nvl\\Content\\Models\\ContentBlock>',
            'new_return' => 'Illuminate\\Contracts\\Pagination\\LengthAwarePaginator<int, Nvl\\Content\\Data\\ContentBlockData>',
            'replacement' => ContentBlockData::class,
            'replacement_api' => 'Nvl\\Content\\Actions\\ListContentBlocksAction::execute(FilterSet $filterSet, ContentActorData $actor, int $perPage = 25)',
            'contract' => [
                'surface' => 'method',
                'class' => ListContentBlocksAction::class,
                'method' => 'execute',
                'parameters' => [
                    'Nvl\\Filterable\\Data\\FilterSet $filterSet',
                    'Nvl\\Content\\Data\\ContentActorData $actor',
                    'int $perPage = 25',
                ],
                'return_type' => LengthAwarePaginator::class,
                'generic_return' => 'LengthAwarePaginator<int, ContentBlockData>',
            ],
            'test_evidence' => ['packages/nvl/content/tests/Feature/ContentContractRegressionTest.php'],
            'guide_anchor' => 'content-read-results',
        ],
        'Nvl\\Content\\Actions\\ListContentPlacementsAction::execute' => [
            'kind' => 'return-shape',
            'package' => 'content',
            'since' => '1.0.7',
            'removed' => '2.0',
            'old_return' => 'Illuminate\\Support\\Collection<int, Nvl\\Content\\Models\\ContentPlacement>',
            'new_return' => 'Illuminate\\Support\\Collection<int, Nvl\\Content\\Data\\ContentPlacementData>',
            'replacement' => ContentPlacementData::class,
            'replacement_api' => 'Nvl\\Content\\Actions\\ListContentPlacementsAction::execute(Model&ContentOwner $owner, string $group, ContentActorData $actor, bool $includeBlocks = false)',
            'contract' => [
                'surface' => 'method',
                'class' => ListContentPlacementsAction::class,
                'method' => 'execute',
                'parameters' => [
                    'Illuminate\\Database\\Eloquent\\Model&Nvl\\Content\\Contracts\\ContentOwner $owner',
                    'string $group',
                    'Nvl\\Content\\Data\\ContentActorData $actor',
                    'bool $includeBlocks = false',
                ],
                'return_type' => Collection::class,
                'generic_return' => 'Collection<int, ContentPlacementData>',
            ],
            'test_evidence' => ['packages/nvl/content/tests/Feature/ContentContractRegressionTest.php'],
            'guide_anchor' => 'content-read-results',
        ],
        'Nvl\\Content\\Content::block' => [
            'kind' => 'return-shape',
            'package' => 'content',
            'since' => '1.0.7',
            'removed' => '2.0',
            'old_return' => 'Nvl\\Content\\Models\\ContentBlock',
            'new_return' => 'Nvl\\Content\\Data\\ContentBlockData',
            'replacement' => ContentBlockData::class,
            'replacement_api' => 'Nvl\\Content\\Content::block(ContentBlock|string $block, ContentActorData $actor): ContentBlockData',
            'contract' => [
                'surface' => 'method',
                'class' => Content::class,
                'method' => 'block',
                'parameters' => [
                    'Nvl\\Content\\Models\\ContentBlock|string $block',
                    'Nvl\\Content\\Data\\ContentActorData $actor',
                ],
                'return_type' => ContentBlockData::class,
            ],
            'test_evidence' => ['packages/nvl/content/tests/Feature/ContentContractRegressionTest.php'],
            'guide_anchor' => 'content-read-results',
        ],
        'Nvl\\Content\\Content::blocks' => [
            'kind' => 'return-shape',
            'package' => 'content',
            'since' => '1.0.7',
            'removed' => '2.0',
            'old_return' => 'Illuminate\\Contracts\\Pagination\\LengthAwarePaginator<int, Nvl\\Content\\Models\\ContentBlock>',
            'new_return' => 'Illuminate\\Contracts\\Pagination\\LengthAwarePaginator<int, Nvl\\Content\\Data\\ContentBlockData>',
            'replacement' => ContentBlockData::class,
            'replacement_api' => 'Nvl\\Content\\Content::blocks(FilterSet $filters, ContentActorData $actor, int $perPage = 25)',
            'contract' => [
                'surface' => 'method',
                'class' => Content::class,
                'method' => 'blocks',
                'parameters' => [
                    'Nvl\\Filterable\\Data\\FilterSet $filters',
                    'Nvl\\Content\\Data\\ContentActorData $actor',
                    'int $perPage = 25',
                ],
                'return_type' => LengthAwarePaginator::class,
                'generic_return' => 'LengthAwarePaginator<int, ContentBlockData>',
            ],
            'test_evidence' => ['packages/nvl/content/tests/Feature/ContentContractRegressionTest.php'],
            'guide_anchor' => 'content-read-results',
        ],
        'Nvl\\Content\\Content::placements' => [
            'kind' => 'return-shape',
            'package' => 'content',
            'since' => '1.0.7',
            'removed' => '2.0',
            'old_return' => 'Illuminate\\Support\\Collection<int, Nvl\\Content\\Models\\ContentPlacement>',
            'new_return' => 'Illuminate\\Support\\Collection<int, Nvl\\Content\\Data\\ContentPlacementData>',
            'replacement' => ContentPlacementData::class,
            'replacement_api' => 'Nvl\\Content\\Content::placements(Model&ContentOwner $owner, string $group, ContentActorData $actor)',
            'contract' => [
                'surface' => 'method',
                'class' => Content::class,
                'method' => 'placements',
                'parameters' => [
                    'Illuminate\\Database\\Eloquent\\Model&Nvl\\Content\\Contracts\\ContentOwner $owner',
                    'string $group',
                    'Nvl\\Content\\Data\\ContentActorData $actor',
                ],
                'return_type' => Collection::class,
                'generic_return' => 'Collection<int, ContentPlacementData>',
            ],
            'test_evidence' => ['packages/nvl/content/tests/Feature/ContentContractRegressionTest.php'],
            'guide_anchor' => 'content-read-results',
        ],
        'Nvl\\Content\\Facades\\Content::block' => [
            'kind' => 'return-shape',
            'package' => 'content',
            'since' => '1.0.7',
            'removed' => '2.0',
            'old_return' => 'Nvl\\Content\\Models\\ContentBlock',
            'new_return' => 'Nvl\\Content\\Data\\ContentBlockData',
            'replacement' => ContentBlockData::class,
            'replacement_api' => 'Nvl\\Content\\Facades\\Content::block(ContentBlock|string $block, ContentActorData $actor): ContentBlockData',
            'contract' => [
                'surface' => 'facade',
                'class' => ContentFacade::class,
                'target_class' => Content::class,
                'method' => 'block',
                'parameters' => [
                    'Nvl\\Content\\Models\\ContentBlock|string $block',
                    'Nvl\\Content\\Data\\ContentActorData $actor',
                ],
                'return_type' => ContentBlockData::class,
                'facade_declaration' => '@method static ContentBlockData block(ContentBlock|string $block, ContentActorData $actor)',
            ],
            'test_evidence' => ['packages/nvl/content/tests/Feature/ContentContractRegressionTest.php'],
            'guide_anchor' => 'content-read-results',
        ],
        'Nvl\\Content\\Facades\\Content::blocks' => [
            'kind' => 'return-shape',
            'package' => 'content',
            'since' => '1.0.7',
            'removed' => '2.0',
            'old_return' => 'Illuminate\\Contracts\\Pagination\\LengthAwarePaginator<int, Nvl\\Content\\Models\\ContentBlock>',
            'new_return' => 'Illuminate\\Contracts\\Pagination\\LengthAwarePaginator<int, Nvl\\Content\\Data\\ContentBlockData>',
            'replacement' => ContentBlockData::class,
            'replacement_api' => 'Nvl\\Content\\Facades\\Content::blocks(FilterSet $filters, ContentActorData $actor, int $perPage = 25)',
            'contract' => [
                'surface' => 'facade',
                'class' => ContentFacade::class,
                'target_class' => Content::class,
                'method' => 'blocks',
                'parameters' => [
                    'Nvl\\Filterable\\Data\\FilterSet $filters',
                    'Nvl\\Content\\Data\\ContentActorData $actor',
                    'int $perPage = 25',
                ],
                'return_type' => LengthAwarePaginator::class,
                'generic_return' => 'LengthAwarePaginator<int, ContentBlockData>',
                'facade_declaration' => '@method static LengthAwarePaginator<int, ContentBlockData> blocks(FilterSet $filters, ContentActorData $actor, int $perPage = 25)',
            ],
            'test_evidence' => ['packages/nvl/content/tests/Feature/ContentContractRegressionTest.php'],
            'guide_anchor' => 'content-read-results',
        ],
        'Nvl\\Content\\Facades\\Content::placements' => [
            'kind' => 'return-shape',
            'package' => 'content',
            'since' => '1.0.7',
            'removed' => '2.0',
            'old_return' => 'Illuminate\\Support\\Collection<int, Nvl\\Content\\Models\\ContentPlacement>',
            'new_return' => 'Illuminate\\Support\\Collection<int, Nvl\\Content\\Data\\ContentPlacementData>',
            'replacement' => ContentPlacementData::class,
            'replacement_api' => 'Nvl\\Content\\Facades\\Content::placements(Model&ContentOwner $owner, string $group, ContentActorData $actor)',
            'contract' => [
                'surface' => 'facade',
                'class' => ContentFacade::class,
                'target_class' => Content::class,
                'method' => 'placements',
                'parameters' => [
                    'Illuminate\\Database\\Eloquent\\Model&Nvl\\Content\\Contracts\\ContentOwner $owner',
                    'string $group',
                    'Nvl\\Content\\Data\\ContentActorData $actor',
                ],
                'return_type' => Collection::class,
                'generic_return' => 'Collection<int, ContentPlacementData>',
                'facade_declaration' => '@method static Collection<int, ContentPlacementData> placements(Model&ContentOwner $owner, string $group, ContentActorData $actor)',
            ],
            'test_evidence' => ['packages/nvl/content/tests/Feature/ContentContractRegressionTest.php'],
            'guide_anchor' => 'content-read-results',
        ],
        'Nvl\\Seo\\Actions\\GetSeoProfileAction::execute' => [
            'kind' => 'return-shape',
            'package' => 'seo',
            'since' => '1.0.7',
            'removed' => '2.0',
            'old_return' => 'Nvl\\Seo\\Models\\SeoProfile',
            'new_return' => 'Nvl\\Seo\\Data\\SeoProfileData',
            'replacement' => SeoProfileData::class,
            'replacement_api' => 'Nvl\\Seo\\Actions\\GetSeoProfileAction::execute(SeoProfile|string $profile): SeoProfileData',
            'contract' => [
                'surface' => 'method',
                'class' => GetSeoProfileAction::class,
                'method' => 'execute',
                'parameters' => [
                    'Nvl\\Seo\\Models\\SeoProfile|string $profile',
                ],
                'return_type' => SeoProfileData::class,
            ],
            'test_evidence' => ['packages/nvl/seo/tests/Feature/SeoConsumerContractsTest.php'],
            'guide_anchor' => 'seo-read-results',
        ],
        'Nvl\\Seo\\Actions\\ListSeoProfilesAction::execute' => [
            'kind' => 'return-shape',
            'package' => 'seo',
            'since' => '1.0.7',
            'removed' => '2.0',
            'old_return' => 'Illuminate\\Contracts\\Pagination\\LengthAwarePaginator<int, Nvl\\Seo\\Models\\SeoProfile>',
            'new_return' => 'Illuminate\\Contracts\\Pagination\\LengthAwarePaginator<int, Nvl\\Seo\\Data\\SeoProfileData>',
            'replacement' => SeoProfileData::class,
            'replacement_api' => 'Nvl\\Seo\\Actions\\ListSeoProfilesAction::execute(SeoProfileQuery $query)',
            'contract' => [
                'surface' => 'method',
                'class' => ListSeoProfilesAction::class,
                'method' => 'execute',
                'parameters' => [
                    'Nvl\\Seo\\Data\\SeoProfileQuery $query',
                ],
                'return_type' => LengthAwarePaginator::class,
                'generic_return' => 'LengthAwarePaginator<int, SeoProfileData>',
            ],
            'test_evidence' => ['packages/nvl/seo/tests/Feature/SeoConsumerContractsTest.php'],
            'guide_anchor' => 'seo-read-results',
        ],
    ],
];
