<?php

declare(strict_types=1);

/**
 * Canonical package-family metadata shared by local quality tooling.
 *
 * @return array{
 *     packages: list<string>,
 *     internal_dependencies: array<string, list<string>>,
 *     database_tested: list<string>,
 *     stateful: list<string>
 * }
 */
return [
    'packages' => [
        'support',
        'data',
        'auth',
        'csv',
        'filterable',
        'translatable',
        'primitives',
        'settings',
        'activity',
        'taxonomy',
        'media',
        'mail-notifications',
        'content',
        'comments',
        'templates',
        'metafields',
        'pages',
        'translations',
        'seo',
        'forms',
    ],
    'internal_dependencies' => [
        'activity' => ['data', 'support'],
        'auth' => [],
        'comments' => ['data', 'filterable', 'media'],
        'content' => ['data', 'filterable', 'media', 'support', 'translatable'],
        'csv' => ['data'],
        'data' => [],
        'filterable' => ['data'],
        'forms' => ['data', 'filterable', 'support', 'translatable'],
        'media' => ['data', 'filterable', 'support', 'translatable'],
        'mail-notifications' => [],
        'metafields' => ['data', 'support', 'translatable'],
        'pages' => ['content', 'data', 'filterable', 'metafields', 'seo', 'translatable'],
        'primitives' => ['data'],
        'seo' => ['data', 'translatable'],
        'settings' => ['data'],
        'support' => [],
        'taxonomy' => ['data', 'translatable'],
        'templates' => ['content', 'data', 'filterable', 'media', 'translatable'],
        'translatable' => ['data'],
        'translations' => ['data', 'filterable', 'support'],
    ],
    'database_tested' => [
        'activity',
        'auth',
        'comments',
        'content',
        'filterable',
        'forms',
        'media',
        'mail-notifications',
        'metafields',
        'pages',
        'seo',
        'settings',
        'taxonomy',
        'templates',
        'translations',
    ],
    'stateful' => [
        'activity',
        'auth',
        'comments',
        'content',
        'forms',
        'media',
        'mail-notifications',
        'metafields',
        'pages',
        'seo',
        'settings',
        'taxonomy',
        'templates',
        'translations',
    ],
];
